version: '3.7'
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - '.:/black_widow'
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:12.1
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
