default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
local_default: &local_default
  username: postgres
  host: db
  password:
development:
  <<: *default
  <<: *local_default
  database: black_widow_development
test:
  <<: *default
  <<: *local_default
  database: black_widow_test
production:
  <<: *default
  database: black_widow_production
  username: black_widow
  password: <%= ENV['BLACK_WIDOW_DATABASE_PASSWORD'] %>
